[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["header_manipulation"]
  icon = "docs/icon.png"
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "header_manipulation"
  org = "yashodperera"
  version = "1.1.0"

